server:
  port: 10010
spring:
  application:
    name: ly-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  ignored-services:
    - upload-service # 忽略upload-service服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #配置禁止使用的头信息，这里设置为null,否则set-cookie无效
ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
leyou:
  jwt:
    pubKeyPath:  E:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item